"use client";

import { useEffect, useState } from "react";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import { db } from "@/lib/firebase";

type Flashback = { id: string; title: string; year: number; imageUrl: string; uploadedAt: string };
export default function FlashbackSection() {
  const [memories, setMemories] = useState<Flashback[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<Flashback | null>(null); const [failed, setFailed] = useState<string[]>([]);
  useEffect(() => { const unsubscribe = onSnapshot(query(collection(db, "flashback"), orderBy("year", "desc")), snapshot => { setMemories(snapshot.docs.map(document => ({ id: document.id, ...document.data() } as Flashback))); setLoading(false); }, () => { setLoading(false); }); return unsubscribe; }, []);
  return <div><p className="text-sm font-bold uppercase tracking-widest text-orange-600">Past celebrations & memories</p><h2 className="mt-2 text-3xl font-black text-slate-900">Utsav Flashback</h2><p className="mt-3 text-slate-600">A live collection of Colony Bois pandal themes, devotion, and beautiful memories.</p>{loading ? <div className="mt-7 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="aspect-[3/4] animate-pulse rounded-2xl bg-orange-100"/>)}</div> : memories.length === 0 ? <div className="mt-7 rounded-2xl border border-dashed border-orange-300 bg-orange-50 p-10 text-center"><div className="text-4xl">📸</div><h3 className="mt-3 font-bold text-slate-900">Memories are coming soon</h3><p className="mt-2 text-sm text-slate-600">Our admins will add previous Utsav photos here.</p></div> : <div className="mt-7 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">{memories.map(memory => <button key={memory.id} onClick={() => setSelected(memory)} className="group relative aspect-[3/4] overflow-hidden rounded-2xl border-2 border-orange-200 bg-orange-50 text-left shadow-sm transition hover:border-orange-500 hover:shadow-lg hover:shadow-orange-100">{failed.includes(memory.id) ? <div className="grid h-full place-items-center p-4 text-center"><span className="text-4xl">🐘</span><span className="mt-2 text-sm font-bold text-orange-700">Image unavailable</span></div> : <img src={memory.imageUrl} alt={`${memory.year} ${memory.title}`} className="h-full w-full object-cover transition duration-300 group-hover:scale-105" onError={() => setFailed(current => [...current, memory.id])}/>}<span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950/80 to-transparent px-3 pb-3 pt-10 text-sm font-black text-white">{memory.year}</span></button>)}</div>}{selected && <div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/90 p-4" role="dialog" aria-modal="true" aria-label={`${selected.year} flashback`}><button onClick={() => setSelected(null)} className="absolute right-5 top-5 rounded-full bg-white p-2 text-slate-900">✕</button><div className="max-h-full max-w-4xl overflow-hidden rounded-2xl bg-black"><img src={selected.imageUrl} alt={`${selected.year} ${selected.title}`} className="max-h-[80vh] w-auto object-contain" onError={() => setFailed(current => [...current, selected.id])}/><p className="bg-white px-4 py-3 font-bold text-slate-900">{selected.year} Highlights · {selected.title}</p></div></div>}</div>;
}
