"use client";
import { useEffect, useState } from "react";
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query } from "firebase/firestore";
import Button from "@/components/ui/Button";
import Card from "@/components/ui/Card";
import Modal from "@/components/ui/Modal";
import { db } from "@/lib/firebase";
import type { PandalEvent } from "@/types";
export default function AdminEvents() { const [open, setOpen] = useState(false); const [events, setEvents] = useState<PandalEvent[]>([]); const [title, setTitle] = useState(""); const [eventDate, setEventDate] = useState(""); const [timeSlot, setTimeSlot] = useState(""); const [venue, setVenue] = useState(""); const [description, setDescription] = useState(""); useEffect(() => onSnapshot(query(collection(db, "events"), orderBy("eventDate", "asc")), snapshot => setEvents(snapshot.docs.map(document => ({ id: document.id, ...document.data() } as PandalEvent))), () => setEvents([])), []); const save = async () => { if (!title || !eventDate || !timeSlot || !venue) return; await addDoc(collection(db, "events"), { title, eventDate, timeSlot, venue, description, status: "upcoming", createdAt: new Date().toISOString() }); setTitle(""); setEventDate(""); setTimeSlot(""); setVenue(""); setDescription(""); setOpen(false); }; return <div><div className="flex items-center justify-between"><div><h1 className="text-3xl font-black text-slate-900">Pandal events & schedule</h1><p className="mt-2 text-slate-600">Create and publish festival activities for residents.</p></div><Button onClick={() => setOpen(true)}>+ Create event</Button></div><div className="mt-7 grid gap-4 md:grid-cols-3">{events.length === 0 ? <Card className="col-span-full p-8 text-center text-slate-600">No events created yet.</Card> : events.map(event => <Card className="p-5" key={event.id}><span className="text-xs font-bold uppercase tracking-widest text-orange-600">{event.eventDate}</span><h2 className="mt-3 font-bold text-slate-900">{event.title}</h2><p className="mt-2 text-sm text-slate-600">{event.timeSlot} · {event.venue}</p><button onClick={() => void deleteDoc(doc(db, "events", event.id))} className="mt-4 text-xs font-bold text-rose-600">Delete event</button></Card>)}</div><Modal open={open} onClose={() => setOpen(false)} title="Create festival event"><div className="space-y-3"><input value={title} onChange={event => setTitle(event.target.value)} placeholder="Event title" className="w-full rounded-xl border border-orange-200 p-3"/><input value={eventDate} onChange={event => setEventDate(event.target.value)} type="date" className="w-full rounded-xl border border-orange-200 p-3"/><input value={timeSlot} onChange={event => setTimeSlot(event.target.value)} placeholder="Time slot" className="w-full rounded-xl border border-orange-200 p-3"/><input value={venue} onChange={event => setVenue(event.target.value)} placeholder="Venue" className="w-full rounded-xl border border-orange-200 p-3"/><textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Description" className="min-h-24 w-full rounded-xl border border-orange-200 p-3"/><Button onClick={() => void save()} className="w-full">Publish event</Button></div></Modal></div>; }
