"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import Card from "@/components/ui/Card";
import WelcomeBanner from "@/components/layout/WelcomeBanner";
import { auth } from "@/lib/firebase";
import { useAuth } from "@/lib/auth-context";

type User = { id: string; name?: string; email?: string; role?: "member" | "admin" | "super_admin"; status?: "pending" | "active" | "suspended" };
type Data = { users: User[]; finance: { approved: number; cash: number; upi: number; pending: number } };
const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;

export default function SuperDashboardPage() {
  const { uid, role, status, loading } = useAuth(); const router = useRouter();
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { try { const token = await auth.currentUser?.getIdToken(); const response = await fetch("/api/super-admin", { headers: { Authorization: `Bearer ${token || ""}` } }); const json = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(json.error || "Unable to load protected data."); setData(json); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load protected data."); } }, []);
  useEffect(() => { if (!loading && (role !== "super_admin" || status !== "active")) router.replace("/login"); }, [loading, role, status, router]);
  useEffect(() => { if (role === "super_admin" && status === "active") void load(); }, [role, status, load]);
  const users = useMemo(() => data?.users || [], [data]);
  const update = async (user: User, patch: Record<string, string>) => { if (user.id === uid || !window.confirm("Apply this protected user access change?")) return; try { setBusy(user.id); const token = await auth.currentUser?.getIdToken(); const response = await fetch("/api/super-admin", { method: "POST", headers: { Authorization: `Bearer ${token || ""}`, "Content-Type": "application/json" }, body: JSON.stringify({ action: "user_update", targetId: user.id, ...patch }) }); if (!response.ok) throw new Error("Update failed."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Update failed."); } finally { setBusy(""); } };
  if (loading || role !== "super_admin" || status !== "active") return <p className="text-slate-600">Checking secure Super Admin access…</p>;
  return <div className="space-y-7"><div className="flex flex-wrap items-center justify-between gap-3"><WelcomeBanner title="Super Admin Control Centre" text="Protected user access and financial oversight."/><Link href="/admin/dashboard" className="rounded-xl border border-orange-300 px-4 py-2 text-sm font-bold text-orange-700">← Admin Dashboard</Link></div>{error && <Card className="border-rose-200 bg-rose-50 p-4 text-rose-700">{error}</Card>}{!data ? <Card className="p-8 text-center text-slate-500">Loading protected data…</Card> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[money(data.finance.approved), "Approved collection"], [money(data.finance.cash), "Cash collection"], [money(data.finance.upi), "UPI collection"], [money(data.finance.pending), "Pending collection"]].map(([value, label]) => <Card key={label} className="p-5"><p className="text-2xl font-black text-orange-600">{value}</p><p className="mt-2 text-sm text-slate-600">{label}</p></Card>)}</div><Card className="overflow-hidden"><div className="border-b border-orange-100 p-5"><h2 className="font-black text-slate-900">User access control</h2><p className="mt-1 text-sm text-slate-600">Role and status changes are protected and audited.</p></div><div className="overflow-x-auto"><table className="min-w-[720px] w-full text-sm"><thead className="bg-orange-50 text-left text-xs uppercase text-slate-600"><tr>{["User", "Role", "Status", "Actions"].map(item => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody className="divide-y divide-orange-50">{users.map(user => <tr key={user.id}><td className="px-4 py-3"><b>{user.name || "Unnamed"}</b><p className="text-xs text-slate-500">{user.email || user.id}</p></td><td className="px-4 py-3 capitalize">{user.role?.replace("_", " ")}</td><td className="px-4 py-3 capitalize">{user.status}</td><td className="px-4 py-3">{user.id === uid ? <span className="text-xs text-slate-400">Self-protected</span> : <div className="flex gap-2"><select disabled={busy === user.id} value={user.role || "member"} onChange={event => void update(user, { role: event.target.value })} className="rounded border border-slate-300 p-1"><option value="member">Member</option><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select><button disabled={busy === user.id} onClick={() => void update(user, { status: user.status === "suspended" ? "active" : "suspended" })} className="rounded border border-rose-300 px-2 py-1 text-xs font-bold text-rose-700">{user.status === "suspended" ? "Restore" : "Suspend"}</button></div>}</td></tr>)}</tbody></table></div></Card></>}</div>;
}
