"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { auth } from "@/lib/firebase";
import { useAuth } from "@/lib/auth-context";
import Card from "@/components/ui/Card";
import WelcomeBanner from "@/components/layout/WelcomeBanner";

type User = { id: string; name?: string; email?: string; role?: "member" | "admin" | "super_admin"; status?: string; createdAt?: { toDate?: () => Date } | string };
type Data = { users: User[]; counts: Record<string, number>; finance: Record<string, number> };
const rupees = (n = 0) => `₹${Number(n).toLocaleString("en-IN")}`;

export default function SuperDashboard() {
  const { uid, role, status, loading } = useAuth(); const router = useRouter();
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const [search, setSearch] = useState(""); const [adjustment, setAdjustment] = useState(""); const [reason, setReason] = useState(""); const [reference, setReference] = useState("");
  const call = useCallback(async (method: "GET" | "POST", body?: Record<string, unknown>) => { const token = await auth.currentUser?.getIdToken(); const res = await fetch("/api/super-admin", { method, headers: { Authorization: `Bearer ${token || ""}`, ...(body ? { "Content-Type": "application/json" } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }); const json = await res.json() as Data & { error?: string }; if (!res.ok) throw new Error(json.error || "Request failed."); return json; }, []);
  const load = useCallback(async () => { try { setError(""); setData(await call("GET")); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load the protected dashboard."); } }, [call]);
  useEffect(() => { if (!loading && (role !== "super_admin" || status !== "active")) router.replace("/login"); }, [loading, role, status, router]);
  useEffect(() => { if (uid && role === "super_admin" && status === "active") void load(); }, [uid, role, status, load]);
  const users = useMemo(() => (data?.users ?? []).filter(u => `${u.name || ""} ${u.email || ""}`.toLowerCase().includes(search.toLowerCase())), [data, search]);
  const updateUser = async (user: User, patch: Record<string, unknown>) => { if (user.id === uid) return; const label = patch.role === "super_admin" ? "grant Super Admin access" : patch.status === "suspended" ? "suspend this user" : "change this user"; if (!window.confirm(`Confirm: ${label}? This action is audited.`)) return; try { setBusy(user.id); await call("POST", { action: "user_update", targetId: user.id, ...patch }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Update failed."); } finally { setBusy(""); } };
  const reconcile = async () => { if (!window.confirm("Record this treasury adjustment? It cannot be silently changed later.")) return; try { setBusy("adjust"); await call("POST", { action: "treasury_adjustment", amount: Number(adjustment), reason, reference }); setAdjustment(""); setReason(""); setReference(""); } catch (e) { setError(e instanceof Error ? e.message : "Adjustment failed."); } finally { setBusy(""); } };
  if (loading || !uid || role !== "super_admin" || status !== "active") return <p className="text-slate-600">Checking secure access…</p>;
  const active = (r: string) => data?.users.filter(u => u.role === r && u.status === "active").length ?? 0;
  return <div className="space-y-7"><WelcomeBanner title="Super Admin Control Centre" text="Protected system-wide controls, financial oversight, and audited access management." />
    {error && <Card className="border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</Card>}
    {!data ? <Card className="p-8 text-center text-slate-500">Loading protected data…</Card> : <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[[data.users.length, "Total users"], [active("member"), "Active members"], [data.users.filter(u => u.status === "pending").length, "Pending registrations"], [data.users.filter(u => u.status === "suspended").length, "Suspended users"], [active("admin"), "Admins"], [active("super_admin"), "Super Admins"]].map(([v,l]) => <Card key={String(l)} className="bg-white p-4"><p className="text-2xl font-black text-orange-600">{v}</p><p className="mt-1 text-xs text-slate-600">{l}</p></Card>)}</div>
      <section><h2 className="mb-3 text-xl font-black text-slate-900">Treasury & Financial Audit</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[[data.finance.approved, "Official approved"], [data.finance.pending, "Pending collection"], [data.finance.cash, "Approved cash"], [data.finance.upi, "Verified online / UPI"], [data.finance.rejected, "Rejected"], [data.finance.voided, "Voided"]].map(([v,l]) => <Card key={String(l)} className="bg-white p-4"><p className="text-xl font-black text-orange-600">{rupees(Number(v))}</p><p className="mt-1 text-xs text-slate-600">{l}</p></Card>)}</div></section>
      <Card className="p-5"><h2 className="font-black text-slate-900">Treasury Reconciliation</h2><p className="mt-1 text-sm text-slate-600">Records an immutable adjustment and audit entry; it never rewrites historical donations.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><input value={adjustment} onChange={e => setAdjustment(e.target.value)} type="number" placeholder="Adjustment ₹ (+/-)" className="rounded-xl border border-slate-300 p-3 text-sm"/><input value={reason} onChange={e => setReason(e.target.value)} placeholder="Reason" className="rounded-xl border border-slate-300 p-3 text-sm"/><input value={reference} onChange={e => setReference(e.target.value)} placeholder="Reference / note" className="rounded-xl border border-slate-300 p-3 text-sm"/><button disabled={busy === "adjust" || !adjustment || !reason || !reference} onClick={() => void reconcile()} className="rounded-xl bg-orange-500 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">Record adjustment</button></div></Card>
      <Card className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="font-black text-slate-900">Users & Roles</h2><p className="text-sm text-slate-600">Role and suspension changes are protected by the server and fully audited.</p></div><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search name or email" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead className="bg-orange-50 text-left text-xs uppercase text-slate-600"><tr>{["User", "Role", "Status", "Registered", "Actions"].map(x => <th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-orange-50">{users.map(user => <tr key={user.id}><td className="px-4 py-3"><b>{user.name || "Unnamed"}</b><p className="text-xs text-slate-500">{user.email || user.id}</p></td><td className="px-4 py-3 capitalize">{user.role?.replace("_", " ")}</td><td className="px-4 py-3 capitalize">{user.status}</td><td className="px-4 py-3 text-xs text-slate-500">{typeof user.createdAt === "string" ? new Date(user.createdAt).toLocaleDateString() : "—"}</td><td className="px-4 py-3">{user.id === uid ? <span className="text-xs text-slate-400">Self-protected</span> : <div className="flex gap-2"><select disabled={busy === user.id} value={user.role || "member"} onChange={e => void updateUser(user, { role: e.target.value })} className="rounded border border-slate-300 p-1 text-xs"><option value="member">Member</option><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select><button disabled={busy === user.id} onClick={() => void updateUser(user, { status: user.status === "suspended" ? "active" : "suspended" })} className="rounded border border-rose-300 px-2 py-1 text-xs font-bold text-rose-700">{user.status === "suspended" ? "Restore" : "Suspend"}</button></div>}</td></tr>)}</tbody></table></div></Card>
      <Card className="p-5"><h2 className="font-black text-slate-900">Existing operational areas</h2><div className="mt-3 flex flex-wrap gap-3">{[["Payment Ledger", "/admin/payment-ledger"], ["Online Chanda", "/admin/chanda-transactions"], ["Events", "/admin/events"], ["Gallery", "/admin/gallery"], ["Committee", "/admin/comity-members"], ["Email", "/admin/email-settings"], ["Audit Logs", "/admin/audit-log"]].map(([label, href]) => <Link key={href} href={href} className="rounded-xl border border-orange-200 px-3 py-2 text-sm font-bold text-orange-700 hover:bg-orange-50">{label} →</Link>)}</div></Card>
    </>}</div>;
}
